### ISSUE TITLE
Daz3D Menu not showing up

### ISSUE THREAD

**Issue by echads** [danielbui78/udtu-unity-package#1]
Great work. Note on
Step 8: Once the Unity Package is installed, select the main menu option Daz3D -> "Open DazToUnity Bridge window".

I had to close and reopen the project to see Daz3D in the menu. I am on Linux but most things work the same on all platforms now a days in Unity so might consider putting something in ()'s mentioning a close/reopen may be required.

I also recieved a null warning and the Editor explained a package was attempting a hot reload or something and that is not allowed. I've seen this before with other things. I'm sure it is just a Unity "Feature" I am in 2020.3.23f1

**Comment by echads** [comment]
The menu item showed up right away on URP.

**Comment by danielbui78** [comment]
Added note to Installation step 8 to close/reopen as suggested. I'll try to look into "hot reloading" of packages to see if there's anything I should change for better compatibility. Thanks.
